include: package:lint/analysis_options_package.yaml

linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Good packages document everything
    public_member_api_docs: true

    avoid_classes_with_only_static_members: false
