name: lan_scanner
description: A package that allows discovering network devices via multi-threaded ICMP pings.
version: 3.4.0
homepage: https://github.com/ivirtex/lan_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_ping: ^6.1.2

dev_dependencies:
  dart_code_metrics: ^4.13.0
  import_sorter: ^4.6.0
  lint: ^1.8.2
  test: ^1.20.2
